#!/usr/bin/env python3
"""Regenerate test/vectors.h -- reference values for the host math tests."""
import random
p = 2**256 - 2**32 - 977
Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
n  = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
assert (Gy*Gy - Gx**3 - 7) % p == 0
def inv(a): return pow(a, p-2, p)
def add(A, B):
    if A is None: return B
    if B is None: return A
    if A[0] == B[0] and (A[1]+B[1]) % p == 0: return None
    s = (3*A[0]*A[0]*inv(2*A[1]) if A == B else (B[1]-A[1])*inv(B[0]-A[0])) % p
    x = (s*s - A[0] - B[0]) % p
    return (x, (s*(A[0]-x) - A[1]) % p)
def mul(k, Pt=(Gx, Gy)):
    R = None
    while k:
        if k & 1: R = add(R, Pt)
        Pt = add(Pt, Pt); k >>= 1
    return R
assert mul(n-1)[0] == Gx
def L(v): return "{" + ",".join("0x%016XULL" % ((v >> (64*i)) & (2**64-1)) for i in range(4)) + "}"
random.seed(7)
print("// auto-generated by tools/gen_vectors.py -- do not edit")
print("struct MulVec { uint64_t a[4], b[4], r[4]; };")
cs = [(random.randrange(p), random.randrange(p)) for _ in range(64)]
cs += [(p-1, p-1), (p-1, 1), (0, 12345), (1, 1), (2**256-1-(2**32+977), 2)]
print("static const MulVec kMul[] = {")
for a, b in cs: print("  {%s,%s,%s}," % (L(a), L(b), L(a*b % p)))
print("};\nstatic const int kMulN = %d;" % len(cs))
print("struct AddVec { uint64_t a[4], b[4], s[4], d[4], i[4]; };")
av = [(random.randrange(p), random.randrange(1, p)) for _ in range(32)]
av += [(p-1, p-1), (0, 1)]
print("static const AddVec kAdd[] = {")
for a, b in av:
    print("  {%s,%s,%s,%s,%s}," % (L(a), L(b), L((a+b) % p), L((a-b) % p), L(inv(b))))
print("};\nstatic const int kAddN = %d;" % len(av))
print("struct EcVec { uint64_t k[4], x[4], y[4]; };")
ks = [1, 2, 3, 7, 0xDEADBEEF, 2**40-1, 2**128+12345, n-1,
      0x1234567890ABCDEF1122334455667788AABBCCDDEEFF00112233445566778899 % n,
      random.randrange(1, n), random.randrange(1, n)]
print("static const EcVec kEc[] = {")
for k in ks:
    P = mul(k)
    print("  {%s,%s,%s}," % (L(k), L(P[0]), L(P[1])))
print("};\nstatic const int kEcN = %d;" % len(ks))
